var object={getType:function(a){switch(a){case null:return"Null";case void 0:return"Undefined"}switch(typeof a){case "boolean":return"Boolean";case "number":return"Number";case "string":return"String"}return"Object"},keys:function(a){this.getType(a)!=="Object"&&alert("type error");var b=[],d;for(d in a)a.hasOwnProperty(d)&&b.push(d);return b},isFunction:function(a){return Object.prototype.toString.call(a)==="[object Function]"},isUndefined:function(a){return typeof a==="undefined"},extend:function(a,
b){for(var d in b)a[d]=b[d];return a}};function $A(a){if(!a)return[];if("toArray"in Object(a))return a.toArray();for(var b=a.length||0,d=Array(b);b--;)d[b]=a[b];return d}Function.prototype.argumentNames=function(){var a=this.toString().match(/^[\s\(]*function[^(]*\(([^)]*)\)/)[1].replace(/\/\/.*?[\r\n]|\/\*(?:.|[\r\n])*?\*\//g,"").replace(/\s+/g,"").split(",");return a.length==1&&!a[0]?[]:a};
Function.prototype.bind=function(a){if(arguments.length<2&&object.isUndefined(arguments[0]))return this;var b=this,d=Array.prototype.slice.call(arguments,1);return function(){var c=d,e=arguments;c=c=Array.prototype.slice.call(c,0);for(var f=c.length,g=e.length;g--;)c[f+g]=e[g];return b.apply(a,c)}};Function.prototype.wrap=function(a){var b=this;return function(){for(var d=[b.bind(this)],c=arguments,e=d.length,f=c.length;f--;)d[e+f]=c[f];return a.apply(this,d)}};
var Class=function(){function a(c,e){for(var f in e)c[f]=e[f];return c}function b(){}var d=function(){for(var c in{toString:1})if(c==="toString")return false;return true}();return{create:function(){function c(){this.initialize.apply(this,arguments)}var e=null,f=$A(arguments);if(object.isFunction(f[0]))e=f.shift();a(c,Class.Methods);c.superclass=e;c.subclasses=[];if(e){b.prototype=e.prototype;c.prototype=new b;e.subclasses.push(c)}e=0;for(var g=f.length;e<g;e++)c.addMethods(f[e]);if(!c.prototype.initialize)c.prototype.initialize=
Prototype.emptyFunction;return c.prototype.constructor=c},extend:a,Methods:{addMethods:function(c){var e=this.superclass&&this.superclass.prototype,f=object.keys(c);if(d){c.toString!=Object.prototype.toString&&f.push("toString");c.valueOf!=Object.prototype.valueOf&&f.push("valueOf")}for(var g=0,k=f.length;g<k;g++){var j=f[g],h=c[j];if(e&&object.isFunction(h)&&h.argumentNames()[0]=="$super"){var i=h;h=function(l){return function(){return e[l].apply(this,arguments)}}(j).wrap(i);h.valueOf=i.valueOf.bind(i);
h.toString=i.toString.bind(i)}this.prototype[j]=h}return this}}}}();Function.prototype.context=function(a){var b=this;return function(){return b.apply(a,arguments)}};function DOMUtil(){}DOMUtil.createElement=function(a,b,d){var c;a=document.createElement(a||b.tag);for(c in b)if(typeof b[c]!=="function")switch(c){case "text":a.appendChild(document.createTextNode(b[c]));break;case "className":a.className=b[c];break;default:a.setAttribute(c,b[c])}d&&d.appendChild(a);return a};
function EnvironmentUtil(){}EnvironmentUtil.iPhone=navigator.userAgent.match(/iPhone/i)!==null;EnvironmentUtil.iPod=navigator.userAgent.match(/iPod/i)!==null;EnvironmentUtil.iPad=navigator.userAgent.match(/iPad/i)!==null;EnvironmentUtil.iOS=EnvironmentUtil.iPhone||EnvironmentUtil.iPod||EnvironmentUtil.iPad;EnvironmentUtil.iOS_3=EnvironmentUtil.iOS&&navigator.userAgent.match(/OS 3/i)!==null;EnvironmentUtil.iOS_4=EnvironmentUtil.iOS&&navigator.userAgent.match(/OS 4/i)!==null;
EnvironmentUtil.chrome=navigator.userAgent.match(/Chrome/i)!==null;EnvironmentUtil.safari=navigator.userAgent.match(/Safari/i)!==null;EnvironmentUtil.android=navigator.userAgent.match(/Android/i)!==null;EnvironmentUtil.android_2_1=navigator.userAgent.match(/Android 2.1/i)!==null;EnvironmentUtil.andriod_2_2=navigator.userAgent.match(/Android 2.2/i)!==null;EnvironmentUtil.ie=navigator.userAgent.match(/MSIE/i)!==null;EnvironmentUtil.ie6=navigator.userAgent.match(/MSIE 6/i)!==null;
EnvironmentUtil.ie7=navigator.userAgent.match(/MSIE 8/i)!==null;EnvironmentUtil.firefox=navigator.userAgent.match(/Firefox/i)!==null;EnvironmentUtil.firefox_3=navigator.userAgent.match(/Firefox\/3/i)!==null;
var FControl=Class.create({initialize:function(a,b,d){this.model=a;this.controller=b;this.container=d;this.element=undefined;this.build();this.setListeners();this.update()},build:function(){this.element=DOMUtil.createElement("div",{className:"fdl-control"},this.container)},setListeners:function(){},update:function(){}}),FVideoModel=Class.create({initialize:function(a){this.dispatcher=$(a);this._volume=1;this._height=this._width=this._duration=this._time=0;this._playerState=this._playing=false;this._bytesTotal=
this._bytesLoaded=0;this._fullscreen=false},setSize:function(a,b){if(!(this._width==a&&this._height==b)){this._width=a;this._height=b;this.dispatcher.trigger(FVideoModel.EVENT_RESIZE)}},getWidth:function(){return this._width},setWidth:function(a){if(this._width!==a){this._width=a;this.dispatcher.trigger(FVideoModel.EVENT_RESIZE)}},getHeight:function(){return this._height},setHeight:function(a){if(this._height!==a){this._height=a;this.dispatcher.trigger(FVideoModel.EVENT_RESIZE)}},getVolume:function(){return this._volume},
setVolume:function(a){a=parseFloat(a);a=a>1?1:a<0?0:a;if(this._volume!=a){this._volume=a;this.dispatcher.trigger(FVideoModel.EVENT_VOLUME_UPDATE)}},getTime:function(){return this._time},setTime:function(a){if(this._time!=a){this._time=a;this.dispatcher.trigger(FVideoModel.EVENT_TIME_UPDATE)}},getDuration:function(){return this._duration},setDuration:function(a){if(this._duration!=a){this._duration=a;this.dispatcher.trigger(FVideoModel.EVENT_TIME_UPDATE)}},getPlaying:function(){return this._playing},
setPlaying:function(a){if(this._playing!=a){this._playing=a;this.dispatcher.trigger(FVideoModel.EVENT_PLAY_STATE_CHANGE)}},getPlayerState:function(){return this._playerState},setPlayerState:function(a){if(this._playerState!==a){this._playerState=a;this.dispatcher.trigger(FVideoModel.EVENT_PLAYER_STATE_CHANGE)}},getBytesLoaded:function(){return this._bytesLoaded},setBytesLoaded:function(a){if(this._bytesLoaded!=a){this._bytesLoaded=a;this.dispatcher.trigger(FVideoModel.EVENT_LOAD_PROGRESS)}},getBytesTotal:function(){return this._bytesTotal},
setBytesTotal:function(a){if(this._bytesTotal!=a){this._bytesTotal=a;this.dispatcher.trigger(FVideoModel.EVENT_LOAD_PROGRESS)}},getFullscreen:function(){return this._fullscreen},setFullscreen:function(a){if(this._fullscreen!=a){this._fullscreen=a;this.dispatcher.trigger(FVideoModel.EVENT_TOGGLE_FULLSCREEN)}}});FVideoModel.EVENT_RESIZE="FVideoModelEvent.Resize";FVideoModel.EVENT_METADATA="FVideoModelEvent.Metadata";FVideoModel.EVENT_TIME_UPDATE="FVideoModelEvent.TimeUpdate";
FVideoModel.EVENT_LOAD_PROGRESS="FVideoModelEvent.LoadProgress";FVideoModel.EVENT_VOLUME_UPDATE="FVideoModelEvent.VolumeUpdate";FVideoModel.EVENT_PLAY_STATE_CHANGE="FVideoModelEvent.PlayStateChange";FVideoModel.EVENT_PLAYER_STATE_CHANGE="FVideoModelEvent.PlayerStateChange";FVideoModel.EVENT_TOGGLE_FULLSCREEN="FVideoModelEvent.ToggleFullscreen";FVideoModel.STATE_LOADING="loading";FVideoModel.STATE_BUFFERING="buffering";FVideoModel.STATE_PLAYING="playing";FVideoModel.STATE_PAUSED="paused";
FVideoModel.STATE_STOPPED="stopped";FVideoModel.STATE_SEEKING="seeking";FVideoModel.STATE_ERROR="error";
var FControls=Class.create({initialize:function(a,b,d,c){this.model=a;this.controller=b;this.container=d;this.controls=[];if(c!==undefined){a=c.length;for(b=0;b<a;b++)this.addControl(c[b])}this.setListeners();this.position()},addControl:function(a){if(typeof a==="string")this.controls.push(new window[a](this.model,this.controller,this.container));else if(typeof a==="function")this.controls.push(new a(this.model,this.controller,this.container));else if(typeof a==="object")if(a.tagName!==undefined){this.container.appendChild(a);
$(a).addClass("fdl-control");this.controls.push(a)}},setListeners:function(){$(this.model.dispatcher).bind(FVideoModel.EVENT_RESIZE,this.position.context(this))},position:function(){var a=this.controls.length,b=[],d=0,c;for(c=0;c<a;c++){var e=this.controls[c];e=e.tagName!==undefined?e:e.element;if($(e).hasClass("fdl-control-flexible"))b.push(e);else $(e).hasClass("fdl-control-absolute")||(d+=e.offsetWidth)}a=b.length;d=(this.model.getWidth()-d)/a;for(c=0;c<a;c++)$(b[c]).width(d)}}),FVideoConfiguration=
Class.create({initialize:function(a,b,d,c,e,f,g){c=c||FVideoConfiguration.DEFAULT_SWF;e=e||{};this.width=a||320;this.height=b||240;this.flashOptions={expressInstall:"expressinstall.swf",version:"10",swf:c,variables:e,params:FVideoConfiguration.mergeOptions(FVideoConfiguration.DEFAULT_FLASH_PARAMS,f),attributes:FVideoConfiguration.mergeOptions(FVideoConfiguration.DEFAULT_FLASH_ATTRIBUTES,g)};this.videoOptions=FVideoConfiguration.mergeOptions(FVideoConfiguration.DEFAULT_VIDEO_OPTIONS,d);this.videoOptions.width=
this.width;this.videoOptions.height=this.height}});FVideoConfiguration.DEFAULT_SWF="proxy-player.swf";FVideoConfiguration.DEFAULT_FLASH_ATTRIBUTES={bgcolor:"#000"};FVideoConfiguration.DEFAULT_VIDEO_OPTIONS={audio:false,autoplay:false,autobuffer:false,controls:false,loop:false,preload:false,src:false,poster:false,volume:1};FVideoConfiguration.DEFAULT_FLASH_PARAMS={scale:"noscale",allowScriptAccess:"always",quality:"best",wmode:"transparent",allowFullScreen:"true"};
FVideoConfiguration.mergeOptions=function(a,b){if(b===undefined)return a;var d={},c;for(c in a)d[c]=a[c];for(c in b)d[c]=typeof b[c]==="object"?FVideoConfiguration.mergeOptions(a[c],b[c]):b[c];return d};
var FVideoSources=Class.create({initialize:function(){this.videos=[];this.flashVideo=""},addVideo:function(a,b,d,c){this.videos.push(new FVideoSource(a,b,d));if(c=="true"||c)this.flashVideo=a}}),FVideoSource=Class.create({initialize:function(a,b,d){this.file=a;this.type=b;this.label=d}}),HTMLVideoProxy=Class.create({initialize:function(a,b,d){this.model=a;this.controller=b;this.video=d;this.bufferInterval=false;this.setListeners(this.video)},addVideoSource:function(a,b){var d=document.createElement("source");
d.src=a;if(!EnvironmentUtil.android&&b!==undefined)d.type=b;$(this.video).append(d)},load:function(a){if(a!==undefined)this.video.src=a;this.video.load()},play:function(a){if(a!==undefined)this.video.src=a;this.video.play()},pause:function(){this.video.pause()},stop:function(){this.video.pause();this.video.currentTime=0},seek:function(a){this.video.currentTime=a},setWidth:function(a){this.video.width=parseInt(a)},setHeight:function(a){this.video.height=parseInt(a)},getVolume:function(){return this.video.volume},
setVolume:function(a){this.video.volume=parseFloat(a)},getTime:function(){return this.video.currentTime},isPlaying:function(){return!this.video.paused},setListeners:function(){this.video.addEventListener("metadata",this.handleMetadata.context(this),false);this.video.addEventListener("loadstart",this.handleLoadStart.context(this),false);this.video.addEventListener("loadeddata",this.handleBuffering.context(this),false);this.video.addEventListener("waiting",this.handleBuffering.context(this),false);
this.video.addEventListener("error",this.handleError.context(this),false);this.video.addEventListener("progress",this.handleProgress.context(this),false);this.video.addEventListener("play",this.handlePlay.context(this),false);this.video.addEventListener("playing",this.handlePlay.context(this),false);this.video.addEventListener("pause",this.handlePause.context(this),false);this.video.addEventListener("seeking",this.handleSeek.context(this),false);this.video.addEventListener("seeked",this.handleSeeked.context(this),
false);this.video.addEventListener("ended",this.handleEnd.context(this),false);this.video.addEventListener("volumechange",this.handleVolume.context(this),false);this.video.addEventListener("timeupdate",this.handleTimeUpdate.context(this),false);this.video.addEventListener("durationchange",this.handleDurationChange.context(this),false);$(this.model.dispatcher).bind(FVideoModel.EVENT_RESIZE,this.resize.context(this));$(this.model.dispatcher).bind(FVideoModel.EVENT_VOLUME_UPDATE,function(){this.setVolume(this.model.getVolume())}.context(this))},
resize:function(){this.video.width=parseInt(this.model.getWidth());this.video.height=parseInt(this.model.getHeight())},startBufferInterval:function(){this.bufferInterval=setInterval(this.handleProgress.context(this),10)},handleDurationChange:function(){this.controller._updateDuration(this.video.duration)},handleMetadata:function(){},handleError:function(){this.controller._updatePlayerState(FVideoModel.STATE_ERROR)},handleTimeUpdate:function(){this.controller._updatePlayheadTime(this.video.currentTime)},
handleProgress:function(a){if(this.video.buffered){if(this.video.buffered.length>0){this.controller._updateLoadProgress(this.video.buffered.end(0),this.video.duration);this.video.buffered.end(0)==this.video.duration&&clearInterval(this.bufferInterval)}}else a&&a.loaded&&a.total&&this.controller._updateLoadProgress(a.loaded,a.total)},handleLoadStart:function(){this.controller._updatePlayerState(FVideoModel.STATE_LOADING)},handleBuffering:function(){this.controller._updatePlayerState(FVideoModel.STATE_BUFFERING)},
handlePlay:function(){this.startBufferInterval();this.controller._updateIsPlaying(true);this.controller._updatePlayerState(FVideoModel.STATE_PLAYING)},handlePause:function(){this.controller._updateIsPlaying(false);this.video.currentTime==0&&this.video.paused?this.controller._updatePlayerState(FVideoModel.STATE_STOPPED):this.controller._updatePlayerState(FVideoModel.STATE_PAUSED)},handleSeek:function(){this.controller._updateIsPlaying(false);this.controller._updatePlayerState(FVideoModel.STATE_SEEKING)},
handleSeeked:function(){this.video.paused?this.handlePause():this.handlePlay()},handleEnd:function(){this.controller._updateIsPlaying(false);this.controller._updatePlayerState(FVideoModel.STATE_STOPPED)},handleVolume:function(){this.controller._updateVolume(this.video.volume)}}),FlashVideoProxy=Class.create({initialize:function(a,b,d){this.model=a;this.controller=b;this.video=d;this.setListeners()},setVideo:function(a){this.video=a},addVideoSource:function(){},load:function(a){a?this.video._load(a):
this.video._load()},play:function(a){a?this.video._play(a):this.video._play()},pause:function(){this.video._pause()},stop:function(){this.video._stop()},seek:function(a){this.video._seek(a)},setWidth:function(a){this.video.width=typeof a=="string"?a:a+"px"},setHeight:function(a){this.video.height=typeof a=="string"?a:a+"px"},getVolume:function(){return this.video._getVolume()},setVolume:function(a){this.video._setVolume(a)},setTime:function(a){this.video._setTime(a)},isPlaying:function(){return this.video._isPlaying()},
setListeners:function(){$(this.model.dispatcher).bind(FVideoModel.EVENT_RESIZE,this.resize.context(this));$(this.model.dispatcher).bind(FVideoModel.EVENT_VOLUME_UPDATE,this.handleVolume.context(this))},handleVolume:function(){this.video._setVolume(this.model.getVolume())},resize:function(){this.setWidth(this.model.getWidth());this.setHeight(this.model.getHeight())}}),PlayPauseButton=Class.create(FControl,{initialize:function($super,b,d,c){$super(b,d,c)},build:function($super){$super();$(this.element).addClass("fdl-play-pause")},
setListeners:function(){$(this.element).click(this.handleClick.context(this))},handleClick:function(){this.model.getPlaying()?this.controller.pause():this.controller.play()}}),StopButton=Class.create(FControl,{initialize:function($super,b,d,c){$super(b,d,c)},build:function($super){$super();$(this.element).addClass("fdl-stop")},setListeners:function(){$(this.element).click(this.controller.stop.context(this.controller))}});function MouseUtil(){}
MouseUtil.getRelativeXFromEvent=function(a,b){for(var d=b.offsetLeft;b=b.offsetParent;)d+=b.offsetLeft;return a.clientX-d};
var ProgressBar=Class.create(FControl,{initialize:function($super,b,d,c){$super(b,d,c)},build:function($super){$super();$(this.element).addClass("fdl-control-flexible fdl-progress-bar");this.downloadBar=DOMUtil.createElement("div",{className:"fdl-load-progress"},this.element);this.progressBar=DOMUtil.createElement("div",{className:"fdl-play-progress"},this.element);this.handle=DOMUtil.createElement("div",{className:"fdl-handle"},this.element)},setListeners:function(){$(this.element).mousedown(this.handleMouseDown.context(this));
$(this.controller.container).bind("resize",this.update.context(this));$(this.model.dispatcher).bind(FVideoModel.EVENT_LOAD_PROGRESS,this.update.context(this));$(this.model.dispatcher).bind(FVideoModel.EVENT_TIME_UPDATE,this.update.context(this))},update:function(){var a;a=this.model.getBytesLoaded()/this.model.getBytesTotal()*this.element.offsetWidth;$(this.downloadBar).css({width:a+"px"});a=this.model.getTime()/this.model.getDuration()*this.element.offsetWidth;$(this.progressBar).css({width:a+"px"})},
handleMouseDown:function(){$(this.container).mousemove(this.handleMouseMove.context(this));$(document).mouseup(this.handleMouseUp.context(this))},handleMouseMove:function(a){a=MouseUtil.getRelativeXFromEvent(a,this.element);this.handle.style.left=a+"px";this.controller.seek(a/parseInt(this.element.offsetWidth)*this.model.getDuration())},handleMouseUp:function(a){this.handleMouseMove(a);$(this.container).unbind("mousemove");$(document).unbind("mouseup")}}),TimeDisplay=Class.create(FControl,{initialize:function($super,
b,d,c){this.totalTime=this.currentTime=false;$super(b,d,c)},build:function($super){$super();$(this.element).addClass("fdl-time-display");this.currentTime=DOMUtil.createElement("span",{className:"fdl-current-time"},this.element);this.separator=DOMUtil.createElement("span",{className:"fdl-time-separator"},this.element);this.totalTime=DOMUtil.createElement("span",{className:"fdl-total-time"},this.element)},setListeners:function(){$(this.model.dispatcher).bind(FVideoModel.EVENT_TIME_UPDATE,this.update.context(this))},
update:function(){this.currentTime.innerHTML=this.formatTime(this.model.getTime());this.totalTime.innerHTML=this.formatTime(this.model.getDuration())},formatTime:function(a){var b=parseInt(a%60);a=parseInt(a/60%60);return this.formattedDigit(parseInt(a/60))+":"+this.formattedDigit(a)+":"+this.formattedDigit(b)},formattedDigit:function(a){return a<10?"0"+a:a}}),VolumeControl=Class.create(FControl,{initialize:function($super,b,d,c){this.progressBar=this.wrapper=false;this.numBars=7;this.barWidth=3;
this.maxBarHeight=15;this.lastMouseX=0;$super(b,d,c)},build:function($super){$super();$(this.element).addClass("fdl-volume");this.wrapper=DOMUtil.createElement("div",{className:"fdl-volume-wrapper"},this.element);$(this.element).mousedown(this.handleMouseDown.context(this));for(var b=0;b<this.numBars;b++){var d=Math.ceil(b/this.numBars*this.maxBarHeight),c=this.maxBarHeight-d,e=DOMUtil.createElement("div",{},this.wrapper);e.style.marginTop=c+"px";e.style.width=this.barWidth+"px";e.style.height=d+
"px"}},setListeners:function(){$(this.model.dispatcher).bind(FVideoModel.EVENT_VOLUME_UPDATE,this.update.context(this))},update:function(){for(var a=this.wrapper.children.length,b=Math.round(this.model.getVolume()*a),d=0;d<a;d++){var c=this.wrapper.children[d];d<=b?$(c).addClass("on"):$(c).removeClass("on")}},handleMouseDown:function(a){$(this.element).mousemove(this.handleMouseMove.context(this));$(document).mouseup(this.handleMouseUp.context(this));this.handleMouseMove(a)},handleMouseMove:function(a){this.lastMouseX=
a=MouseUtil.getRelativeXFromEvent(a,this.element);this.controller._updateVolume(a/this.wrapper.offsetWidth)},handleMouseUp:function(){this.controller._updateVolume(this.lastMouseX/this.wrapper.offsetWidth);$(this.element).unbind("mousemove");$(document).unbind("mouseup")}}),FullscreenButton=Class.create(FControl,{initialize:function($super,b,d,c){$super(b,d,c);this.viewportHeight=this.viewportWidth=0;this.origWidth=this.model.getWidth();this.origHeight=this.model.getHeight();this.origPosition=false;
this.getViewportSize()},build:function($super){$super();$(this.element).addClass("fdl-fullscreen")},setListeners:function(){$(this.element).click(this.toggleFullscreen.context(this));$(this.model.dispatcher).bind(FVideoModel.EVENT_TOGGLE_FULLSCREEN,this.handleFullscreen.context(this))},handleFullscreen:function(){this.model.getFullscreen()?this.enterFullscreen():this.exitFullscreen()},toggleFullscreen:function(){this.controller.setFullscreen(!this.model.getFullscreen())},size:function(){this.getViewportSize();
this.controller.setSize(this.viewportWidth,this.viewportHeight)},enterFullscreen:function(){this.size();$(window).resize(this.size.context(this))},exitFullscreen:function(){$(window).unbind("resize");this.controller.setSize(this.origWidth,this.origHeight)},getViewportSize:function(){if(typeof window.innerWidth!="undefined"){this.viewportWidth=window.innerWidth;this.viewportHeight=window.innerHeight}else if(typeof document.documentElement!="undefined"&&typeof document.documentElement.clientWidth!=
"undefined"&&document.documentElement.clientWidth!=0){this.viewportWidth=document.documentElement.clientWidth;this.viewportHeight=document.documentElement.clientHeight}else{this.viewportWidth=document.getElementsByTagName("body")[0].clientWidth;this.viewportHeight=document.getElementsByTagName("body")[0].clientHeight}}}),FVideo=Class.create({VERSION:"1.0.0",initialize:function(a,b,d,c,e){this.container=typeof a==="string"?$(a).get(0):a;this.options=b||new FVideoConfiguration;this.sources=d||new FVideoSources;
this.controlsClasses=c?c:FVideo.defaultControls;this.readyCallback=e;this._videoElement=this._isVideoEmbedded=this._isVideoReady=this.controls=this.proxy=this.model=false;this._useHTMLVideo=true;this._isReady=this._initialized=false;this._lastState="";this._init()},load:function(){this.proxy.load()},play:function(a){if(a)this.proxy.play(a);else this.model.getPlaying()?this.proxy.pause():this.proxy.play()},pause:function(){this.proxy.pause()},stop:function(){this.proxy.stop()},seek:function(a){this.proxy.seek(parseFloat(a))},
setSize:function(a,b){this.model.setSize(a,b)},getWidth:function(){return this.model.getWidth()},setWidth:function(a){this.model.setWidth(a)},getHeight:function(){return this.model.getHeight()},setHeight:function(a){this.model.setHeight(a)},getTime:function(){return this.proxy.getTime()},getVolume:function(){return this.model.getVolume()},setVolume:function(a){this.model.setVolume(a)},getFullscreen:function(){return this.model.getFullscreen()},setFullscreen:function(a){this.model.setFullscreen(a)},
addVideoSource:function(a,b){this.proxy.addVideoSource(a,b)},fallback:function(){this.player.innerHTML="";this._createSourceAnchors(this.player)},destroy:function(){this.player&&this.player.parentNode&&this.player.parentNode.removeChild(this.player)},setVideo:function(a){if(this._videoElement=$("#"+a.id).get(0))this._isVideoEmbedded=true},_videoReady:function(){this._isVideoReady=true;this._checkReady()},_startupVideo:function(){if(!this._isReady){this._isReady=true;this.proxy=this._createVideoProxy();
for(var a=this.sources.videos.length,b=0;b<a;b++){var d=this.sources.videos[b];this.addVideoSource(d.file,d.type)}this.setVolume(this.options.videoOptions.volume);this.setSize(this.options.width,this.options.height);if(this.controlsClasses)if(this.controlsClasses.length>0){this.controlsContainer=DOMUtil.createElement("div",{className:"fdl-controls"},this.container);this.controlsContainer.onmousedown=function(){return false};this.controlsContainer.onselectstart=function(){return false};this.controls=
new FControls(this.model,this,this.controlsContainer,this.controlsClasses)}this.readyCallback(this);$(this.container).trigger(FVideo.EVENT_PLAYER_READY)}},_updatePlayheadTime:function(a){this.model.setTime(a)},_updateDuration:function(a){this.model.setDuration(a)},_updateIsPlaying:function(a){this.model.setPlaying(a)},_updatePlayerState:function(a){this.model.setPlayerState(a)},_updateVolume:function(a){this.model.setVolume(a)},_updateLoadProgress:function(a,b){this.model.setBytesTotal(b);this.model.setBytesLoaded(a)},
_init:function(){this.player=DOMUtil.createElement("div",{className:"player"},this.container);this.playerId=parseInt(Math.random()*1E5,10);FVideo.instances[this.playerId]=this;this._useHTMLVideo=this._canBrowserPlayVideo();this._videoElement=this._createVideo();this.model=new FVideoModel(this.container);this._addModelListeners();this._useHTMLVideo?this._videoReady():this.setSize(this.options.width,this.options.height)},_checkReady:function(){this._isVideoReady&&this._isVideoEmbedded&&this._startupVideo()},
_canBrowserPlayVideo:function(){return document.createElement("video").play!==undefined},_createVideo:function(){return this._useHTMLVideo?this._createHTMLVideoObject():this._createFlashVideoObject()},_createHTMLVideoObject:function(){var a=document.createElement("video");FVideo.applyAttributes(a,this.options.videoOptions);this._createSourceAnchors(a);this.player.appendChild(a);this._isVideoEmbedded=true;return a},_createSourceAnchors:function(a){for(var b=this.sources.videos.length,d=0;d<b;d++){var c=
this.sources.videos[d],e=document.createElement("a");e.href=c.file;e.setAttribute("data-type",c.type);e.innerHTML=c.label;a.appendChild(e)}},_createFlashVideoObject:function(){var a="player-wrapper-"+this.playerId,b="fdl-player-"+this.playerId;DOMUtil.createElement("div",{id:a},this.player);this.options.flashOptions.attributes.id=b;this.options.flashOptions.variables.playerId=this.playerId;this.options.flashOptions.variables.src=this.sources.flashVideo;this.options.flashOptions.variables.autoplay=
this.options.videoOptions.autoplay;swfobject.embedSWF(this.options.flashOptions.swf,a,this.options.width,this.options.height,this.options.flashOptions.version,this.options.flashOptions.expressInstall,this.options.flashOptions.variables,this.options.flashOptions.params,this.options.flashOptions.attributes);this._findFlashPlayer(b);return null},_findFlashPlayer:function(a){var b=this;b.flashFinderInterval=setInterval(function(){var d=$("#"+a);if(d.length>0){b.setVideo(d.get(0));b._checkReady();clearInterval(b.flashFinderInterval)}},
10)},_createVideoProxy:function(){return this._useHTMLVideo?new HTMLVideoProxy(this.model,this,this._videoElement):new FlashVideoProxy(this.model,this,this._videoElement)},_enterFullscreen:function(){$(this.container).addClass("fdl-fullscreen")},_exitFullscreen:function(){$(this.container).removeClass("fdl-fullscreen")},_addModelListeners:function(){$(this.model.dispatcher).bind(FVideoModel.EVENT_RESIZE,this._handleResize.context(this));$(this.model.dispatcher).bind(FVideoModel.EVENT_PLAYER_STATE_CHANGE,
this._handleStateChange.context(this));$(this.model.dispatcher).bind(FVideoModel.EVENT_TOGGLE_FULLSCREEN,this._handleFullscreen.context(this))},_handleStateChange:function(){$(this.container).removeClass(this._lastState);this._lastState=this.model.getPlayerState();$(this.container).addClass(this._lastState)},_handleResize:function(){var a=this.model.getWidth(),b=this.model.getHeight();b=typeof b=="string"?b:b+"px";this.container.style.width=typeof a=="string"?a:a+"px";this.container.style.height=
b},_handleFullscreen:function(){this.model.getFullscreen()?this._enterFullscreen():this._exitFullscreen()}});FVideo.EVENT_PLAYER_READY="FVideo:PlayerReady";FVideo.defaultControls=null;FVideo.instances={};
FVideo.activateAll=function(a){$(".fdl-video").each(function(){var b=$("video",this).get(0);b.pause();b.src="";EnvironmentUtil.firefox_3&&this.load();var d=new FVideoSources;$("source",b).each(function(){d.addVideo(this.src,this.type,this.getAttribute("data-label"),this.getAttribute("data-flash-default")||false)});var c={},e;if(b.width)c.width=b.width;if(b.height)c.height=b.height;if(b.getAttribute("data-flash-swf"))e=b.getAttribute("data-flash-swf");if(b.getAttribute("data-controls"))c.controls=
b.getAttribute("data-controls");if(b.getAttribute("data-volume"))c.volume=b.getAttribute("data-volume");if(b.getAttribute("data-autoplay"))c.autoplay=b.getAttribute("data-autoplay");if(b.getAttribute("data-preload"))c.preload=b.getAttribute("data-preload");if(b.getAttribute("data-loop"))c.loop=b.getAttribute("data-loop");if(b.getAttribute("data-poster"))c.poster=b.getAttribute("data-poster");if(b.getAttribute("data-src"))c.src=b.getAttribute("data-src");var f=b.getAttribute("data-controls-list");
if(f!==undefined&&f!==null){f=f.replace(" ","");var g=f.split(",")}b=new FVideoConfiguration(b.width,b.height,c,e);this.innerHTML="";new FVideo(this,b,d,g,a)})};FVideo.applyAttributes=function(a,b){for(var d in b){d=d.toLowerCase();if(d=="width"||d=="height")a[d]=parseInt(b[d],10);else if(b[d]&&typeof b[d]==="string"){if(b[d].toLowerCase()!=="false")a[d]=b[d]}else if(b[d])a[d]=b[d]}};
